### ISSUE TITLE
Question:  Is there a way to stream logs from a dedicated server?

### ISSUE THREAD

**Issue by dyerrington** [jaumebecks/valheim-server-notifier#2]
I know Valheim uses Valve protocol for server info which is really quite easy to connect to and use from a script.  Ultimately, I would like to push events from my dedicated server hosted remotely to my Discord server.  Does this project assume the end-user is running the bot application on the same machine?

**Comment by jaumebecks** [comment]
Hi @dyerrington, 

> Does this project assume the end-user is running the bot application on the same machine?

Nope. I'm running it in my remote valheim server actually

> I would like to push events from my dedicated server hosted remotely to my Discord server

So, this is exatcly what I do in my own setup  :smile:

**Comment by jaumebecks** [comment]
Closing question due to inactivity, considered as answered :smiley:
